[package]
name           = "azure_sdk_for_rust"
version        = "0.6.1"
description    = "Rust wrappers around Microsoft Azure REST APIs"
readme         = "README.md"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>", "Dong Liu <doliu@microsoft.com>"]
license        = "Apache-2.0"
repository     = "https://github.com/MindFlavor/AzureSDKForRust"
documentation  = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"
homepage       = "https://github.com/MindFlavor/AzureSDKForRust"

keywords       = ["sdk", "azure", "rest", "iot", "cloud"]
categories     = ["api-bindings"]

[dependencies]
ring         = "0.12.1"
RustyXML     = "0.1.1"
base64       = "0.9.1"
chrono       = "0.4.2"
env_logger   = "0.5.10"
futures      = "0.1.21"
hyper        = "0.11.26"
hyper-tls    = "0.1.3"
log          = "0.4.1"
mime         = "0.3.7"
native-tls   = "0.1.5"
quick-error  = "1.2.1"
serde        = "1.0.54"
serde_derive = "1.0.54"
serde_json   = "1.0.17"
time         = "0.1.40"
tokio-core   = "0.1.17"
url          = "1.7.0"
uuid         = "0.6.3"
smallvec     = { version = "0.6", features = ["serde"] }

[features]
test_e2e       = []
