[package]
name             = "azure_sdk_for_rust"
version          = "0.3.1"
description      = "Rust wrappers around Microsoft Azure REST APIs"
readme           = "README.md"
authors          = ["Francesco Cogno <francesco.cogno@outlook.com>", "Dong Liu <doliu@microsoft.com>"]
license          = "Apache-2.0"
repository       = "https://github.com/MindFlavor/AzureSDKForRust"
documentation    = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"

keywords         = ["sdk", "azure", "rest", "iot", "cloud"]
categories       = ["api-bindings"]

[[bin]]
name             = "main"
doc              = false

[dependencies]
chrono       = "0.3.0"
rust-crypto  = "*"
quick-error  = "*"
RustyXML     = "*"
log          = "*"
env_logger   = "*"
uuid         = "*"
time         = "*"
url          = "*"
base64       = "*"
serde        = "*"
serde_json   = "*"
serde_derive = "*"
hyper        = "*"

tokio        = "*"
tokio-core   = "*"
futures      = "*"
hyper-tls    = "*"
native-tls   = "*"

[features]
test_e2e         = []
