[package]
name           = "azure_sdk_for_rust"
version        = "0.7.2"
description    = "Rust wrappers around Microsoft Azure REST APIs"
readme         = "README.md"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>", "Max Gortman <mgortman@microsoft.com>", "Dong Liu <doliu@microsoft.com>"]
license        = "Apache-2.0"
repository     = "https://github.com/MindFlavor/AzureSDKForRust"
documentation  = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"
homepage       = "https://github.com/MindFlavor/AzureSDKForRust"

keywords       = ["sdk", "azure", "rest", "iot", "cloud"]
categories     = ["api-bindings"]

[dependencies]
ring         = "*"
RustyXML     = "*"
base64       = "*"
chrono       = "*"
env_logger   = "*"
futures      = "0.1.21"
hyper        = "0.11.27"
hyper-tls    = "0.1.3"
log          = "*"
mime         = "*"
native-tls   = "*"
quick-error  = "*"
serde        = "*"
serde_derive = "*"
serde_json   = "*"
time         = "*"
tokio-core   = "*"
url          = "*"
uuid         = "*"
rust-crypto  = "*"
failure	     = "*"
smallvec     = { version = "0.6", features = ["serde"] }

[features]
test_e2e       = []
