[package]
name = "azure_sdk_for_rust"
version = "0.3.0"
description = "Rust wrappers around Microsoft Azure REST APIs"
readme = "README.md"
authors = ["Francesco Cogno <francesco.cogno@outlook.com>", "Dong Liu <doliu@microsoft.com>"]
license = "Apache-2.0"
repository = "https://github.com/MindFlavor/AzureSDKForRust"
documentation = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"

[[bin]]
name = "main"
doc = false

[dependencies]
chrono = "0.3.1"
rust-crypto = "0.2.36"
quick-error = "1.2.0"
RustyXML = "0.1.1"
mime = "0.2.3"
log = "0.3.7"
env_logger = "0.4.2"
uuid = "0.5.0"
time = "0.1.37"
url = "1.4.0"
base64 = "0.5.2"
serde = "1.0.2"
serde_json = "1.0.1"
serde_derive = "1.0.2"
hyper = "0.10.9"
hyper-native-tls = "0.2.2"

# clippy="*"

[features]
test_e2e = []
