[package]
name = "azure_sdk_for_rust"
version = "0.1.2"
authors = ["Francesco Cogno <francesco.cogno@outlook.com>"]

[[bin]]
name = "main"
doc = false

[dependencies]
chrono = "*"
rust-crypto = "^0.2"
rustc-serialize = "*"
RustyXML = "*"
mime = "*"
log = "0.3"
env_logger = "0.3"
uuid = "^0.1"

clippy="*"

[dependencies.hyper]
version = "*"
default-features = true

[dependencies.url]
git = "https://github.com/servo/rust-url"
