[package]
name = "azure_sdk_for_rust"
version = "0.0.4"
authors = ["Francesco Cogno <francesco.cogno@outlook.com>"]

[dependencies]
chrono = "*"
rust-crypto = "^0.2"
rustc-serialize = "*"
RustyXML = "*"
mime = "*"

[dependencies.hyper]
version = "*"
default-features = true

[dependencies.url]
git = "https://github.com/servo/rust-url"
