[package]
name           = "azure_sdk_for_rust"
version        = "0.4.3"
description    = "Rust wrappers around Microsoft Azure REST APIs"
readme         = "README.md"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>", "Dong Liu <doliu@microsoft.com>"]
license        = "Apache-2.0"
repository     = "https://github.com/MindFlavor/AzureSDKForRust"
documentation  = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"

keywords       = ["sdk", "azure", "rest", "iot", "cloud"]
categories     = ["api-bindings"]

[[bin]]
name           = "main"
doc            = false

[dependencies]
RustyXML       = "0.1.1"
base64         = "0.6.0"
chrono         = "0.4.0"
env_logger     = "0.4.3"
futures        = "0.1.14"
hyper          = "0.11.1"
hyper-tls      = "0.1.2"
log            = "0.3.8"
mime           = "0.3.2"
native-tls     = "0.1.4"
quick-error    = "1.2.0"
rust-crypto    = "0.2.36"
serde          = "1.0.9"
serde_derive   = "1.0.9"
serde_json     = "1.0.2"
time           = "0.1.38"
tokio          = "0.0.0"
tokio-core     = "0.1.8"
url            = "1.5.1"
uuid           = "0.5.1"

[features]
test_e2e       = []
